// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/maei/mongodb_mock_hexa/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// APIInterfaceGRPCArticle is an autogenerated mock type for the APIInterfaceGRPCArticle type
type APIInterfaceGRPCArticle struct {
	mock.Mock
}

// SendArticle provides a mock function with given fields: ctx, article
func (_m *APIInterfaceGRPCArticle) SendArticle(ctx context.Context, article *domain.Article) (string, error) {
	ret := _m.Called(ctx, article)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Article) string); ok {
		r0 = rf(ctx, article)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Article) error); ok {
		r1 = rf(ctx, article)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
