// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	articlepb "github.com/maei/mongodb_mock_hexa/src/article/proto"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// ArticleAPIClient is an autogenerated mock type for the ArticleAPIClient type
type ArticleAPIClient struct {
	mock.Mock
}

// StoreArticle provides a mock function with given fields: ctx, in, opts
func (_m *ArticleAPIClient) StoreArticle(ctx context.Context, in *articlepb.ArticleRequest, opts ...grpc.CallOption) (*articlepb.ArticleResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *articlepb.ArticleResponse
	if rf, ok := ret.Get(0).(func(context.Context, *articlepb.ArticleRequest, ...grpc.CallOption) *articlepb.ArticleResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*articlepb.ArticleResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *articlepb.ArticleRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
