// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ArticleControllerInterface is an autogenerated mock type for the ArticleControllerInterface type
type ArticleControllerInterface struct {
	mock.Mock
}

// FindArticle provides a mock function with given fields: c
func (_m *ArticleControllerInterface) FindArticle(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostArticle provides a mock function with given fields: c
func (_m *ArticleControllerInterface) PostArticle(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
