// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	articlepb "github.com/maei/mongodb_mock_hexa/src/article/proto"

	mock "github.com/stretchr/testify/mock"
)

// ArticleAPIServer is an autogenerated mock type for the ArticleAPIServer type
type ArticleAPIServer struct {
	mock.Mock
}

// StoreArticle provides a mock function with given fields: _a0, _a1
func (_m *ArticleAPIServer) StoreArticle(_a0 context.Context, _a1 *articlepb.ArticleRequest) (*articlepb.ArticleResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *articlepb.ArticleResponse
	if rf, ok := ret.Get(0).(func(context.Context, *articlepb.ArticleRequest) *articlepb.ArticleResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*articlepb.ArticleResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *articlepb.ArticleRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
