// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GRPCArticleInterface is an autogenerated mock type for the GRPCArticleInterface type
type GRPCArticleInterface struct {
	mock.Mock
}

// SendArticle provides a mock function with given fields:
func (_m *GRPCArticleInterface) SendArticle() {
	_m.Called()
}
